server:
  port: 8888
spring:
  application:
    name: admin
  datasource:
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      hikari:
        username: root
        password: lmc@2017
        driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.newfeelings.user.entity

dubbo:
  scan:
    base-packages: com.newfeelings.user.dubbo.service
  protocol:
    port: 8060
    name: dubbo
  registry:
    address: spring-cloud://localhost